### ISSUE TITLE
User can see graph data of how many users make up each rank in each region

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Looking-To-Play#7]
## ⚙️ Feature

User can see graph data of how many users make up each rank in each region

## 📐 Functionality

Users can visit a user stats page that will have breakdowns of how many users exist on the app that are broken
down into how many users are in each region divided by ranks in the form of graphs

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/99226300/181350706-9ebd6f55-9c89-4619-9c8c-fd568df8f3a7.png)
![image](https://user-images.githubusercontent.com/99226300/181350756-2478e87f-cb42-47d4-9256-baf6ffbc481e.png)

![image](https://user-images.githubusercontent.com/99226300/181356788-8b805b08-25ac-47fe-8893-315536e7ef3d.png)
![image](https://user-images.githubusercontent.com/99226300/181356710-318cdaca-de56-4f31-b605-a271cd518044.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include users table
    - [x] user table should have userId, mmRankId, faceitRank, regionId, timeAvailable, recentStats, profilePicture and team 
- [x] Update `data.sql` to include dummy data for 20 users across 5 regions

### ☁️ Server Tasks

- [x] Update `server/index.js` to include GET request from API to pull user data from database based on region
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
    - [x] parse json response into JS
    - [x] assign grouped user data to new variables based on the ranks of the players being pulled.

### ⚡ Client Tasks

- [ ] Create a component to render graph onto the page
    - [x] gather data result from API request
    - [x] in player-charts.js, using chart.js, create two new bar charts to represent matchmaking and faceit ranks on profiles
    - [x] create 2 buttons to switch view between matchmaking ranks and faceit ranks by changing the hash
    - [x] make sure that the hash in the URL is representative of the current page
    - [x] add a dropdown selector to change the region being represented on the graph.
- [ ] Update component to render navbar 
    - [x] add logo in top right
    - [x] create 2 buttons with no frame for player stats and find users (neither needs to work yet)
    - [x] add the long logo to the top left that only shows when the screen expands to desktop size

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
