### ISSUE TITLE
User can sign out

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Looking-To-Play#8]
## ⚙️ Feature

User can sign out

## 📐 Functionality

User can open the drawer menu and click the sign out button to exit the app and be brought back to the sign in page

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/99226300/182736447-87ed83ba-a16a-48f4-b478-66cbf620e73e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] on App.jsx
    - [ ] add a handleSignOut method to the app component that will. . .
        - [ ] remove the token item from local storage
        - [ ] set the user state to null
    - [ ] add handleSignOut to the context provider

- [ ] on Navbar.jsx
    - [ ] get the handleSignOut out of the context
    - [ ] add a sign out button in the top right corner
    - [ ] add an onClick listener to the sign-out button to call handleSignOut

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
